name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -race -coverprofile=coverage.out -covermode=atomic ./...

    - uses: codecov/codecov-action@v1
      with:
        files: ./coverage.out